openapi: 3.0.0
info:
  title: OpenRouter Chat Completions API
  version: 1.0.0
  description: API для взаимодействия с моделями чата OpenRouter.
servers:
  - url: https://openrouter.ai/api/v1
tags:
  - name: Chat
paths:
  /chat/completions:
    post:
      security: 
        - bearerAuth: []
      tags: 
        - Chat
      summary: Create a chat completion
      description: Отправляет запрос к модели чата для генерации ответа на основе предоставленных сообщений.
      operationId: createChatCompletion
      requestBody:
        description: Объект запроса для завершения чата.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                  description: Название используемой модели
                  example: google/gemini-2.0-flash-001
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        description: Роль автора этого сообщения.
                        example: user
                      content:
                        type: array
                        description: Содержимое сообщения. Может быть массивом текстовых объектов и/или объектов URL-адресов изображений.
                        items:
                          oneOf:
                            - type: object
                              required:
                                - type
                                - text
                              properties:
                                type:
                                  type: string
                                  example: text
                                text:
                                  type: string
                                  description: Текстовое содержимое сообщения.
                                  example: What's in this image?
                            - type: object
                              required:
                                - type
                                - image_url
                              properties:
                                type:
                                  type: string
                                  example: image_url
                                image_url:
                                  type: object
                                  required:
                                    - url
                                  properties:
                                    url:
                                      type: string
                                      description: Base64-представление изображения
                                      example: data:image/jpeg;base64,/9j/4AAQSkZJRgA...
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: chatcmpl-8xW...
                  object:
                    type: string
                    example: chat.completion
                  created:
                    type: integer
                    example: 1708892400
                  model:
                    type: string
                    example: gpt-4.1
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          example: 0
                        message:
                          type: object
                          properties:
                            role:
                              type: string
                              example: assistant
                            content:
                              type: string
                              example: The image shows a long wooden boardwalk winding through a natural...
                        logprobs:
                          type: object
                          nullable: true
                        finish_reason:
                          type: string
                          example: stop
                  usage:
                    type: object
                    properties:
                      prompt_tokens:
                        type: integer
                        example: 100
                      completion_tokens:
                        type: integer
                        example: 50
                      total_tokens:
                        type: integer
                        example: 150
        "400":
          description: Bad request Error
          content:
            application/json: 
              schema: 
                type: object
                properties: 
                  error:
                    type: object
                    properties: 
                      code:
                        type: string
                      message: 
                        type: string
                      param:
                        type: string
                      type:
                        type: string
        "401":
          description: Unauthorised Error
        "429" :
          description: Too many requests Error
        "500":
          description: Internal server Error
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer